package com.indeas.gestaoempreiteira.modelo;

public enum TipoEquipamento {

	CB("CAMINHÃO BASCULHANTE"),
	CBET("CAMINHÃO BETONEIRA"),
	CC("CAMINHÃO COMBOIO"),
	CE("CAMINHÃO ESPARGIDOR"),
	CI("CAMINHÃO IRRIGADORA"),
	CTA("CAMINHÃO TANQUE ABASTECEDOR"),
	CMB("CONJUNTO MÓVEL BRITAGEM"),
	CT("CARREGA TUDO"),
	CV("CAVALO MECANICO"),
	EH("ESCAVADEIRA HIDRÁULICA"),
	EX("EXTRUSORA"),
	IB("IMPLEMENTO BASCULANTE"),
	JU("CAMINHÃO JUMBO"),
	MB("MOTOR BOMBA"),
	MN("MOTONIVELADORA"),
	MT("MOTOCICLETA"),
	PC("PÁ CARREGADEIRA"),
	PR("PRANCHA RETA"),
	RC("ROLO COMPACTADOR"),
	RD("RECICLADORA"),
	RE("RETROESCAVADEIRA"),
	RP("ROLO DE PNEUS COMPACTADOR"),
	RS("REBOQUE SINALIZAÇÃO"),
	RT("ROLO TANDEM"),
	TE("TRATOR DE ESTEIRAS"),
	TP("TRATOR DE PNEUS"),
	TQ("TANQUE SEMI-REBOQUE"),
	UM("CAMINHÃO REBOQUE USINA MICRO"),
	UQ("USINA DE ASFALTO QUENTE"),
	VA("VIBROACABADORA"),
	VL("VEICULOS LEVE"),
	VM("VASSOURA MECÂNICA")
	;
	private String nome;

	public String getNome() {
		return nome;
	}

	private TipoEquipamento(String nome) {
		this.nome = nome;
	}
	
}
